// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU3T07ebBnwNcxD_jCl8980i8Ht7F0c88',
    appId: '1:955479935416:web:f07a76ecf2459d467da74d',
    messagingSenderId: '955479935416',
    projectId: 'diu-lost-found',
    authDomain: 'diu-lost-found.firebaseapp.com',
    storageBucket: 'diu-lost-found.firebasestorage.app',
    measurementId: 'G-LPQKKJQYFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1wtsvtONrszaJsWZ5wXfrclLC4VZzocA',
    appId: '1:955479935416:android:9586a434429b4d6a7da74d',
    messagingSenderId: '955479935416',
    projectId: 'diu-lost-found',
    storageBucket: 'diu-lost-found.firebasestorage.app',
  );
}
